site: Curso Latex
url: "https://mrleon.space"
title: Curso Latex
description: "Curso para la introducción a la edición académica con Latex para las humanidades y las ciencias sociales"
googlewebfonts: Fira+Code:wght@400;500;700
twitter:
  username: intratextual
  card: summary
  creator: #yourusername
author:
  twitter: intratextual
  name: Alberto R. León
  avatar:
  email: hola@mrleon.space
  url: https://mrleon.space
permalink: pretty

baseurl: "/curso-latex"

highlighter: rouge

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
